window.albumImages = [
  "İkimiz de yakışıklı ve güzelken.jpg",
  "Son arkadaş aktivitemiz.jpg",
  "Altaylardan tunaya...jpg",
  "First dateee.jpg",
  "Endüstrici zorbalama postu.jpg",
  "Bindiğimiz ilk metro.jpg",
  "Bunu koymasam olmazdı.jpg",
  "Thats my girll.jpg",
  "Düştüm.jpg",
  "Sen + Ben = Ankara'da aşk.jpg",
  "Sırada F4 baba kaldı binmediğimiz.jpg",
  "Her bir kartanesi farklıymış derler. Hiç biri sana benzemiyor da ondan.jpg",
  "But I miss you come here.jpg",
  "Pervanelere döndüm seni görünce.jpg",
  "nanak.jpg",
  "Şiir gibi aşkımız var desem yanlış mı olur.jpg",
  "This is my girl.jpg",
  "haftaya giyeceğim tshirt.jpg",
  "bir elmanın iki yarısı....jpg",
  "Teşekkürler hayatım.jpg",
  "İşte o tarihi gün.jpg",
  "Hayal ettim bölüştüğümüzü bir ekmeği oturarak.jpg",
  "Tıpkısının aynısı.jpg",
  "prensesim.jpg",
  "her güzel değilim dediğinde ben.png",
  "Life goals.jpg",
  "Sene 2000 Londra metrosu (tabi yiyen olursa).jpg",
  "Dona kaldım güzelliğine.jpg",
  "bu sayfayı değiştirdim. bunu da koymuş olayım.jpg",
  "Çünkü o senin gülün....jpg"
];
